@echo off
REM Register the MCE web bridge to auto-start (hidden) at Windows logon,
REM then start it in the background right away.
set "VBS=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\mce-web-bridge.vbs"
(
  echo ' Auto-generated by autostart-install.cmd - starts the MCE web bridge hidden at logon
  echo Set sh = CreateObject^("WScript.Shell"^)
  echo sh.Run """%~dp0run-web.cmd""", 0, False
) > "%VBS%"
echo Registered autostart: %VBS%
echo Starting web bridge in background now (no window)...
wscript "%VBS%"
echo Done. To stop the server: stop-web.cmd / To remove autostart: autostart-remove.cmd
pause
